package BSML.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.DefaultNodeEditor;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import com.mbeddr.core.base.behavior.IConfigurationContainer__BehaviorDescriptor;
import com.mbeddr.core.buildconfig.behavior.BCHelper;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.nodeEditor.cellProviders.CellProviderWithRole;
import jetbrains.mps.lang.editor.cellProviders.PropertyCellProvider;
import jetbrains.mps.nodeEditor.EditorManager;
import jetbrains.mps.lang.editor.cellProviders.SingleRoleCellProvider;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.nodeEditor.cellMenu.DefaultChildSubstituteInfo;
import jetbrains.mps.openapi.editor.style.Style;
import jetbrains.mps.editor.runtime.style.StyleImpl;
import jetbrains.mps.editor.runtime.style.StyleAttributes;

public class StateLocalDeclaration_Editor extends DefaultNodeEditor {
  public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
    return this.createCollection_etxv9i_a(editorContext, node);
  }
  private EditorCell createCollection_etxv9i_a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createIndent2(editorContext, node);
    editorCell.setCellId("Collection_etxv9i_a");
    editorCell.setBig(true);
    if (renderingCondition_etxv9i_a0a(node, editorContext)) {
      editorCell.addEditorCell(this.createConstant_etxv9i_a0(editorContext, node));
    }
    editorCell.addEditorCell(this.createConstant_etxv9i_b0(editorContext, node));
    editorCell.addEditorCell(this.createProperty_etxv9i_c0(editorContext, node));
    editorCell.addEditorCell(this.createRefNode_etxv9i_d0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_etxv9i_e0(editorContext, node));
    return editorCell;
  }
  private EditorCell createConstant_etxv9i_a0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "(stable)");
    editorCell.setCellId("Constant_etxv9i_a0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private static boolean renderingCondition_etxv9i_a0a(SNode node, EditorContext editorContext) {
    SNode config = SNodeOperations.cast(IConfigurationContainer__BehaviorDescriptor.findItemOfType_id3R$6B6bL1DB.invoke(BCHelper.findBC(SNodeOperations.getModel(node)), MetaAdapterFactory.getConcept(0x181cb8f23d5e4aa9L, 0xb8cd2e496087f7c8L, 0x58d666a512918588L, "BSML.structure.StateMachineConfigItem").getDeclarationNode()), MetaAdapterFactory.getConcept(0x181cb8f23d5e4aa9L, 0xb8cd2e496087f7c8L, 0x58d666a512918588L, "BSML.structure.StateMachineConfigItem"));
    if (SPropertyOperations.hasValue(config, MetaAdapterFactory.getProperty(0x181cb8f23d5e4aa9L, 0xb8cd2e496087f7c8L, 0x58d666a512918588L, 0x58d666a51291858bL, "bigStepMaximality"), "2", "1")) {
      return SPropertyOperations.getBoolean(node, MetaAdapterFactory.getProperty(0x181cb8f23d5e4aa9L, 0xb8cd2e496087f7c8L, 0x58d666a51294688aL, 0x58d666a5129913f6L, "stable"));
    }
    return false;
  }
  private EditorCell createConstant_etxv9i_b0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "state");
    editorCell.setCellId("Constant_etxv9i_b0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createProperty_etxv9i_c0(EditorContext editorContext, SNode node) {
    CellProviderWithRole provider = new PropertyCellProvider(node, editorContext);
    provider.setRole("name");
    provider.setNoTargetText("<no name>");
    EditorCell editorCell;
    editorCell = provider.createEditorCell(editorContext);
    editorCell.setCellId("property_name");
    editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
    SNode attributeConcept = provider.getRoleAttribute();
    Class attributeKind = provider.getRoleAttributeClass();
    if (attributeConcept != null) {
      EditorManager manager = EditorManager.getInstanceFromContext(editorContext);
      return manager.createNodeRoleAttributeCell(attributeConcept, attributeKind, editorCell);
    } else
    return editorCell;
  }
  private EditorCell createRefNode_etxv9i_d0(EditorContext editorContext, SNode node) {
    SingleRoleCellProvider provider = new StateLocalDeclaration_Editor.contentSingleRoleHandler_etxv9i_d0(node, MetaAdapterFactory.getContainmentLink(0x181cb8f23d5e4aa9L, 0xb8cd2e496087f7c8L, 0x58d666a51294688aL, 0x58d666a5129913f8L, "content"), editorContext);
    return provider.createCell();
  }
  private class contentSingleRoleHandler_etxv9i_d0 extends SingleRoleCellProvider {
    public contentSingleRoleHandler_etxv9i_d0(SNode ownerNode, SContainmentLink containmentLink, EditorContext context) {
      super(ownerNode, containmentLink, context);
    }
    protected EditorCell createChildCell(SNode child) {
      EditorCell editorCell = super.createChildCell(child);
      installCellInfo(child, editorCell);
      return editorCell;
    }
    private void installCellInfo(SNode child, EditorCell editorCell) {
      editorCell.setSubstituteInfo(new DefaultChildSubstituteInfo(myOwnerNode, myContainmentLink.getDeclarationNode(), myEditorContext));
      if (editorCell.getRole() == null) {
        editorCell.setRole("content");
      }
    }
    @Override
    protected EditorCell createEmptyCell() {
      EditorCell editorCell = super.createEmptyCell();
      editorCell.setCellId("empty_content");
      installCellInfo(null, editorCell);
      return editorCell;
    }
    protected String getNoTargetText() {
      return "<no content>";
    }
  }
  private EditorCell createConstant_etxv9i_e0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, ";");
    editorCell.setCellId("Constant_etxv9i_e0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.PUNCTUATION_LEFT, 0, true);
    style.set(StyleAttributes.INDENT_LAYOUT_NEW_LINE, 0, true);
    editorCell.getStyle().putAll(style);
    editorCell.setDefaultText("");
    return editorCell;
  }
}
