#ifndef DIALLERSYSTEMIMPL_H
#define DIALLERSYSTEMIMPL_H


#include <stdint.h>

#include <stddef.h>

#include <stdbool.h>



#ifdef __cplusplus
extern "C" {
#endif

typedef void ((*(DiallerSystemImpl_BindingRef))(void **));
typedef enum DiallerSystemImpl_DiallerSystemImpl__DiallerSystem_EventEnum DiallerSystemImpl_DiallerSystemImpl__DiallerSystem_EventEnum_t;
enum DiallerSystemImpl_DiallerSystemImpl__DiallerSystem_EventEnum{
  DiallerSystemImpl_DiallerSystemImpl__DiallerSystem_EventEnum__DiallerSystemImpl__DiallerSystem__main__dial,
  DiallerSystemImpl_DiallerSystemImpl__DiallerSystem_EventEnum__DiallerSystemImpl__DiallerSystem__main__redial,
  DiallerSystemImpl_DiallerSystemImpl__DiallerSystem_EventEnum__DiallerSystemImpl__DiallerSystem__main__Dialing__Dialer__out,
  DiallerSystemImpl_DiallerSystemImpl__DiallerSystem_EventEnum__DiallerSystemImpl__DiallerSystem__main__Dialing__Dialer__reset,
  DiallerSystemImpl_DiallerSystemImpl__DiallerSystem_EventEnum___sm_terminate_h
};

typedef enum DiallerSystemImpl_DiallerSystemImpl__DiallerSystem_StateEnum DiallerSystemImpl_DiallerSystemImpl__DiallerSystem_StateEnum_t;
enum DiallerSystemImpl_DiallerSystemImpl__DiallerSystem_StateEnum{
  DiallerSystemImpl_DiallerSystemImpl__DiallerSystem_StateEnum__DiallerSystemImpl__DiallerSystem__main__Dialing,
  DiallerSystemImpl_DiallerSystemImpl__DiallerSystem_StateEnum__DiallerSystemImpl__DiallerSystem__main__Dialing__Dialer__WaitForDial,
  DiallerSystemImpl_DiallerSystemImpl__DiallerSystem_StateEnum__DiallerSystemImpl__DiallerSystem__main__Dialing__Dialer__DialDigits,
  DiallerSystemImpl_DiallerSystemImpl__DiallerSystem_StateEnum__DiallerSystemImpl__DiallerSystem__main__Dialing__Redialer__WaitForRedial,
  DiallerSystemImpl_DiallerSystemImpl__DiallerSystem_StateEnum__DiallerSystemImpl__DiallerSystem__main__Dialing__Redialer__RedialDigits,
  DiallerSystemImpl_DiallerSystemImpl__DiallerSystem_StateEnum__DiallerSystemImpl__DiallerSystem__main__Max
};

typedef enum DiallerSystemImpl_DiallerSystemImpl__DiallerSystem_RegionEnum DiallerSystemImpl_DiallerSystemImpl__DiallerSystem_RegionEnum_t;
enum DiallerSystemImpl_DiallerSystemImpl__DiallerSystem_RegionEnum{
  DiallerSystemImpl_DiallerSystemImpl__DiallerSystem_RegionEnum__DiallerSystemImpl__DiallerSystem__main,
  DiallerSystemImpl_DiallerSystemImpl__DiallerSystem_RegionEnum__DiallerSystemImpl__DiallerSystem__main__Dialing__Dialer,
  DiallerSystemImpl_DiallerSystemImpl__DiallerSystem_RegionEnum__DiallerSystemImpl__DiallerSystem__main__Dialing__Redialer
};

typedef enum DiallerSystemImpl_DiallerSystemImpl__DiallerSystem_TransEnum DiallerSystemImpl_DiallerSystemImpl__DiallerSystem_TransEnum_t;
enum DiallerSystemImpl_DiallerSystemImpl__DiallerSystem_TransEnum{
  DiallerSystemImpl_DiallerSystemImpl__DiallerSystem_TransEnum__DiallerSystemImpl__DiallerSystem__main__Dialing__Dialer__t1,
  DiallerSystemImpl_DiallerSystemImpl__DiallerSystem_TransEnum__DiallerSystemImpl__DiallerSystem__main__Dialing__Dialer__t2,
  DiallerSystemImpl_DiallerSystemImpl__DiallerSystem_TransEnum__DiallerSystemImpl__DiallerSystem__main__Dialing__Dialer__t3,
  DiallerSystemImpl_DiallerSystemImpl__DiallerSystem_TransEnum__DiallerSystemImpl__DiallerSystem__main__Dialing__Dialer__t4,
  DiallerSystemImpl_DiallerSystemImpl__DiallerSystem_TransEnum__DiallerSystemImpl__DiallerSystem__main__Dialing__Dialer__t10,
  DiallerSystemImpl_DiallerSystemImpl__DiallerSystem_TransEnum__DiallerSystemImpl__DiallerSystem__main__Dialing__Redialer__t5,
  DiallerSystemImpl_DiallerSystemImpl__DiallerSystem_TransEnum__DiallerSystemImpl__DiallerSystem__main__Dialing__Redialer__t6,
  DiallerSystemImpl_DiallerSystemImpl__DiallerSystem_TransEnum__DiallerSystemImpl__DiallerSystem__main__Dialing__Redialer__t7,
  DiallerSystemImpl_DiallerSystemImpl__DiallerSystem_TransEnum__DiallerSystemImpl__DiallerSystem__main__t8,
  DiallerSystemImpl_DiallerSystemImpl__DiallerSystem_TransEnum__DiallerSystemImpl__DiallerSystem__main__t9
};

int32_t  DiallerSystemImpl_main(int32_t argc, char *(argv[]));

void  DiallerSystemImpl_sm_msg_SM_initialized(char *name, char *loc);

void  DiallerSystemImpl_sm_msg_transition_occur(char *trans_id, char *from, char *to, char *loc);

void  DiallerSystemImpl_sm_msg_trans_enabled(uint32_t num, char *loc);

void  DiallerSystemImpl_sm_msg_start_big_step(char *loc);

void  DiallerSystemImpl_sm_msg_end_big_step(char *loc);

void  DiallerSystemImpl_sm_msg_start_small_step(char *loc);

void  DiallerSystemImpl_sm_msg_end_small_step(char *loc);

void  DiallerSystemImpl_sm_msg_other(char *info, char *loc);


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
