package BSML.behavior;

/*Generated by MPS */

import com.mbeddr.core.base.behavior.IVisibleElementProvider_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.behaviour.DefaultValuesHolder;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public class EndBigStepBlock_BehaviorDescriptor extends AbstractBlock_BehaviorDescriptor implements IVisibleElementProvider_BehaviorDescriptor {
  public boolean virtual_hasVisibleContentsOfType_9136994893370299109(SNode __thisNode__, SNode targetConcept) {
    return DefaultValuesHolder.defaultValue(Boolean.TYPE);
  }
  public Iterable<SNode> virtual_visibleContentsOfType_7139820346881179813(SNode __thisNode__, SNode targetConcept) {
    return null;
  }

  @Override
  public String getConceptFqName() {
    return "BSML.structure.EndBigStepBlock";
  }

}
