package BSML.behavior;

/*Generated by MPS */

import com.mbeddr.core.modules.behavior.ArgumentRef_BehaviorDescriptor;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public class EventArgRef_BehaviorDescriptor extends ArgumentRef_BehaviorDescriptor {

  @Override
  public String getConceptFqName() {
    return "BSML.structure.EventArgRef";
  }

}
