package BSML.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This interface is not involved in the actual method invocation
 */
@Deprecated
public interface IEvent_BehaviorDescriptor extends ISMNamedElement_BehaviorDescriptor {
  public Iterable<SNode> virtual_args_6401416779521097910(SNode thisNode);
  public SNode virtual_binding_6401416779521097926(SNode thisNode);
  public boolean virtual_isInEvent_6401416779521097948(SNode thisNode);
  public boolean virtual_isOutEvent_6401416779521097968(SNode thisNode);
  public boolean virtual_isRendezvousEvent_6401416779521097992(SNode thisNode);
}
