package BSML.behavior;

/*Generated by MPS */

import com.mbeddr.core.statements.behavior.ILocalVarScopeProvider_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This interface is not involved in the actual method invocation
 */
@Deprecated
public interface IRegion_BehaviorDescriptor extends ILocalVarScopeProvider_BehaviorDescriptor, ISMElementScopeProvider_BehaviorDescriptor, ISMNamedElement_BehaviorDescriptor {
  public SNode virtual_initState_6401416779521098065(SNode thisNode);
  public Iterable<SNode> virtual_getContainedOthers_6401416779521098076(SNode thisNode);
  public String virtual_qualifiedRegionName_6401416779521098132(SNode thisNode);
}
