package BSML.behavior;

/*Generated by MPS */

import com.mbeddr.core.base.behavior.IContainerOfUniqueNames_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This interface is not involved in the actual method invocation
 */
@Deprecated
public interface ISMElementScopeProvider_BehaviorDescriptor extends IContainerOfUniqueNames_BehaviorDescriptor {
  public Iterable<SNode> virtual_getContainedElements_6401416779521091820(SNode thisNode);
  public Iterable<SNode> virtual_getVisibleElements_6401416779521091836(SNode thisNode);
}
