package BSML.behavior;

/*Generated by MPS */

import com.mbeddr.core.base.behavior.IIdentifierNamedConcept_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This interface is not involved in the actual method invocation
 */
@Deprecated
public interface ISMNamedElement_BehaviorDescriptor extends ISMElement_BehaviorDescriptor, IIdentifierNamedConcept_BehaviorDescriptor {
  public String virtual_id_6401416779521096403(SNode thisNode);
}
