package BSML.behavior;

/*Generated by MPS */


/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This interface is not involved in the actual method invocation
 */
@Deprecated
public interface IStateMachine_BehaviorDescriptor extends ISMNamedElement_BehaviorDescriptor, ISMElementScopeProvider_BehaviorDescriptor {
}
