package BSML.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This interface is not involved in the actual method invocation
 */
@Deprecated
public interface IState_BehaviorDescriptor extends ISMElementScopeProvider_BehaviorDescriptor, ISMNamedElement_BehaviorDescriptor {
  public boolean virtual_isStable_6401416779521097856(SNode thisNode);
}
