package BSML.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This interface is not involved in the actual method invocation
 */
@Deprecated
public interface ITransition_BehaviorDescriptor extends ISMNamedElement_BehaviorDescriptor {
  public SNode virtual_guard_6401416779521108620(SNode thisNode);
  public SNode virtual_action_6401416779521108631(SNode thisNode);
  public SNode virtual_target_6401416779521108646(SNode thisNode);
  public SNode virtual_source_6401416779521108665(SNode thisNode);
  public int virtual_priority_6401416779521108688(SNode thisNode);
  public Iterable<SNode> virtual_triggers_6401416779521108715(SNode thisNode);
}
