package BSML.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;
import com.mbeddr.core.modules.behavior.IModuleContent_BehaviorDescriptor;
import jetbrains.mps.baseLanguage.behavior.IContainsStatementList_BehaviorDescriptor;
import com.mbeddr.core.base.behavior.IVisibleElementProvider_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.behaviour.DefaultValuesHolder;
import org.jetbrains.mps.openapi.language.SConcept;
import javax.swing.Icon;
import java.util.List;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public class SMGlobalDeclaration_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements IStateMachine_BehaviorDescriptor, IModuleContent_BehaviorDescriptor, IContainsStatementList_BehaviorDescriptor, IVisibleElementProvider_BehaviorDescriptor {
  public boolean virtual_actuallyShowInOutline_3789096399633594747(SNode __thisNode__) {
    return DefaultValuesHolder.defaultValue(Boolean.TYPE);
  }
  public Iterable<SNode> virtual_allReferencedModuleContents_1798411515023042202(SNode __thisNode__) {
    return null;
  }
  public boolean virtual_allowEverythingExceptWhitespace_151435140526267396(SConcept __thisConcept__) {
    return DefaultValuesHolder.defaultValue(Boolean.TYPE);
  }
  public boolean virtual_allowNonIdentifierNames_6584628407655574550(SConcept __thisConcept__) {
    return DefaultValuesHolder.defaultValue(Boolean.TYPE);
  }
  public String virtual_conceptLabel_5470497459580078362(SNode __thisNode__) {
    return null;
  }
  public SNode virtual_createImportedProxy_55677248263987031(SNode __thisNode__) {
    return null;
  }
  public boolean virtual_exportable_6584628407655574574(SConcept __thisConcept__) {
    return DefaultValuesHolder.defaultValue(Boolean.TYPE);
  }
  public Icon virtual_getBreadcrumbIcon_5003834500845999512(SNode __thisNode__) {
    return null;
  }
  public String virtual_getBreadcrumbText_4313262807135907204(SNode __thisNode__) {
    return null;
  }
  public List<SAbstractConcept> virtual_getCommentConcept_6584628407655574603(SConcept __thisConcept__) {
    return null;
  }
  public Iterable<SNode> virtual_getContainedElements_6401416779521091820(SNode __thisNode__) {
    return null;
  }
  public SNode virtual_getDocNodeOrNull_1130241639304546246(SNode __thisNode__) {
    return null;
  }
  public String virtual_getDocTextOrEmpty_3857533489766146434(SNode __thisNode__) {
    return null;
  }
  public String virtual_getFqName_1213877404258(SNode __thisNode__) {
    return null;
  }
  public String virtual_getTraceableProperty_5067982036267369901(SNode __thisNode__) {
    return null;
  }
  public Iterable<SNode> virtual_getUniquelyNamedElements_5095889050031059923(SNode __thisNode__) {
    return null;
  }
  public Iterable<SNode> virtual_getVisibleElements_6401416779521091836(SNode __thisNode__) {
    return null;
  }
  public boolean virtual_hasVisibleContentsOfType_9136994893370299109(SNode __thisNode__, SNode targetConcept) {
    return DefaultValuesHolder.defaultValue(Boolean.TYPE);
  }
  public String virtual_id_6401416779521096403(SNode __thisNode__) {
    return null;
  }
  public boolean virtual_isCommentable_4457953124863306087(SNode __thisNode__, SNode trigger) {
    return DefaultValuesHolder.defaultValue(Boolean.TYPE);
  }
  public boolean virtual_isStatementListCompact_1237546693016(SNode __thisNode__) {
    return DefaultValuesHolder.defaultValue(Boolean.TYPE);
  }
  public boolean virtual_isStatementListCompactable_1237546012856(SNode __thisNode__) {
    return DefaultValuesHolder.defaultValue(Boolean.TYPE);
  }
  public String virtual_kindString_6641971848870642999(SNode __thisNode__) {
    return null;
  }
  public String virtual_mangledNameNew_7475861851228904359(SNode __thisNode__) {
    return null;
  }
  public String virtual_mangledName_1317894735999377422(SNode __thisNode__) {
    return null;
  }
  public boolean virtual_needsReferenceQualifier_1317894735999315639(SNode __thisNode__, SNode sourceModule) {
    return DefaultValuesHolder.defaultValue(Boolean.TYPE);
  }
  public boolean virtual_preventNameMangling_6708182213627106041(SNode __thisNode__) {
    return DefaultValuesHolder.defaultValue(Boolean.TYPE);
  }
  public String virtual_qualifiedName_5470497459578244269(SNode __thisNode__) {
    return null;
  }
  public String virtual_referenceQualifier_1317894735999315602(SNode __thisNode__) {
    return null;
  }
  public String virtual_shortDescriptionForCCMenu_5470497459578304992(SNode __thisNode__) {
    return null;
  }
  public boolean virtual_showInBreadcrumb_1609581366351617259(SNode __thisNode__) {
    return DefaultValuesHolder.defaultValue(Boolean.TYPE);
  }
  public int virtual_sortWeight_7999989049973036118(SNode __thisNode__) {
    return DefaultValuesHolder.defaultValue(Integer.TYPE);
  }
  public Iterable<SNode> virtual_visibleContentsOfType_7139820346881179813(SNode __thisNode__, SNode targetConcept) {
    return null;
  }

  @Override
  public String getConceptFqName() {
    return "BSML.structure.SMGlobalDeclaration";
  }

}
