package BSML.behavior;

/*Generated by MPS */

import com.mbeddr.core.statements.behavior.LocalVariableDeclaration_BehaviorDescriptor;
import jetbrains.mps.lang.core.behavior.IDontSubstituteByDefault_BehaviorDescriptor;
import jetbrains.mps.baseLanguage.behavior.IContainsStatementList_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.behaviour.DefaultValuesHolder;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public class StateLocalDeclaration_BehaviorDescriptor extends LocalVariableDeclaration_BehaviorDescriptor implements IDontSubstituteByDefault_BehaviorDescriptor, IState_BehaviorDescriptor, IContainsStatementList_BehaviorDescriptor {
  public Iterable<SNode> virtual_getContainedElements_6401416779521091820(SNode __thisNode__) {
    return null;
  }
  public Iterable<SNode> virtual_getUniquelyNamedElements_5095889050031059923(SNode __thisNode__) {
    return null;
  }
  public Iterable<SNode> virtual_getVisibleElements_6401416779521091836(SNode __thisNode__) {
    return null;
  }
  public String virtual_id_6401416779521096403(SNode __thisNode__) {
    return null;
  }
  public boolean virtual_isStable_6401416779521097856(SNode __thisNode__) {
    return DefaultValuesHolder.defaultValue(Boolean.TYPE);
  }
  public boolean virtual_isStatementListCompact_1237546693016(SNode __thisNode__) {
    return DefaultValuesHolder.defaultValue(Boolean.TYPE);
  }
  public boolean virtual_isStatementListCompactable_1237546012856(SNode __thisNode__) {
    return DefaultValuesHolder.defaultValue(Boolean.TYPE);
  }

  @Override
  public String getConceptFqName() {
    return "BSML.structure.StateLocalDeclaration";
  }

}
