package BSML.behavior;

/*Generated by MPS */

import com.mbeddr.core.expressions.behavior.Type_BehaviorDescriptor;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public class StateType_BehaviorDescriptor extends Type_BehaviorDescriptor {

  @Override
  public String getConceptFqName() {
    return "BSML.structure.StateType";
  }

}
