package BSML.behavior;

/*Generated by MPS */

import com.mbeddr.core.statements.behavior.Statement_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.behaviour.DefaultValuesHolder;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public class Transition_BehaviorDescriptor extends Statement_BehaviorDescriptor implements ITransition_BehaviorDescriptor {
  public SNode virtual_action_6401416779521108631(SNode __thisNode__) {
    return null;
  }
  public boolean virtual_allowEverythingExceptWhitespace_151435140526267396(SConcept __thisConcept__) {
    return DefaultValuesHolder.defaultValue(Boolean.TYPE);
  }
  public boolean virtual_allowNonIdentifierNames_6584628407655574550(SConcept __thisConcept__) {
    return DefaultValuesHolder.defaultValue(Boolean.TYPE);
  }
  public String virtual_conceptLabel_5470497459580078362(SNode __thisNode__) {
    return null;
  }
  public String virtual_getFqName_1213877404258(SNode __thisNode__) {
    return null;
  }
  public SNode virtual_guard_6401416779521108620(SNode __thisNode__) {
    return null;
  }
  public String virtual_id_6401416779521096403(SNode __thisNode__) {
    return null;
  }
  public int virtual_priority_6401416779521108688(SNode __thisNode__) {
    return DefaultValuesHolder.defaultValue(Integer.TYPE);
  }
  public String virtual_qualifiedName_5470497459578244269(SNode __thisNode__) {
    return null;
  }
  public String virtual_shortDescriptionForCCMenu_5470497459578304992(SNode __thisNode__) {
    return null;
  }
  public boolean virtual_simpleOneLiner_1786180596061315608(SNode __thisNode__) {
    return DefaultValuesHolder.defaultValue(Boolean.TYPE);
  }
  public SNode virtual_source_6401416779521108665(SNode __thisNode__) {
    return null;
  }
  public SNode virtual_target_6401416779521108646(SNode __thisNode__) {
    return null;
  }
  public Iterable<SNode> virtual_triggers_6401416779521108715(SNode __thisNode__) {
    return null;
  }

  @Override
  public String getConceptFqName() {
    return "BSML.structure.Transition";
  }

}
