package BSML.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum BigStepMaximalityEnum {
  _0("TAKE ONE", 0),
  _1("TAKE MANY", 1),
  _2("SYNTACTIC", 2);

  private final String myName;
  public String getName() {
    return myName;
  }
  private final int myValue;
  BigStepMaximalityEnum(String name, int value) {
    myName = name;
    myValue = value;
  }
  public int getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return Integer.toString(myValue);
  }
  public static List<BigStepMaximalityEnum> getConstants() {
    List<BigStepMaximalityEnum> list = ListSequence.fromList(new LinkedList<BigStepMaximalityEnum>());
    ListSequence.fromList(list).addElement(BigStepMaximalityEnum._0);
    ListSequence.fromList(list).addElement(BigStepMaximalityEnum._1);
    ListSequence.fromList(list).addElement(BigStepMaximalityEnum._2);
    return list;
  }
  public static BigStepMaximalityEnum getDefault() {
    return BigStepMaximalityEnum._1;
  }
  public static BigStepMaximalityEnum parseValue(String value) {
    if (value == null) {
      return BigStepMaximalityEnum.getDefault();
    }
    if (value.equals(BigStepMaximalityEnum._0.getValueAsString())) {
      return BigStepMaximalityEnum._0;
    }
    if (value.equals(BigStepMaximalityEnum._1.getValueAsString())) {
      return BigStepMaximalityEnum._1;
    }
    if (value.equals(BigStepMaximalityEnum._2.getValueAsString())) {
      return BigStepMaximalityEnum._2;
    }
    return BigStepMaximalityEnum.getDefault();
  }
}
