package BSML.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum EventLifelineEnum {
  _0("PRESENT IN REMAINDER", 0),
  _1("PRESENT IN NEXT SMALL", 1);

  private final String myName;
  public String getName() {
    return myName;
  }
  private final int myValue;
  EventLifelineEnum(String name, int value) {
    myName = name;
    myValue = value;
  }
  public int getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return Integer.toString(myValue);
  }
  public static List<EventLifelineEnum> getConstants() {
    List<EventLifelineEnum> list = ListSequence.fromList(new LinkedList<EventLifelineEnum>());
    ListSequence.fromList(list).addElement(EventLifelineEnum._0);
    ListSequence.fromList(list).addElement(EventLifelineEnum._1);
    return list;
  }
  public static EventLifelineEnum getDefault() {
    return EventLifelineEnum._0;
  }
  public static EventLifelineEnum parseValue(String value) {
    if (value == null) {
      return EventLifelineEnum.getDefault();
    }
    if (value.equals(EventLifelineEnum._0.getValueAsString())) {
      return EventLifelineEnum._0;
    }
    if (value.equals(EventLifelineEnum._1.getValueAsString())) {
      return EventLifelineEnum._1;
    }
    return EventLifelineEnum.getDefault();
  }
}
