package BSML.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum HierPriorityRegionEnum {
  _0("SCOPE", 0),
  _1("SOURCE", 1),
  _2("TARGET", 2);

  private final String myName;
  public String getName() {
    return myName;
  }
  private final int myValue;
  HierPriorityRegionEnum(String name, int value) {
    myName = name;
    myValue = value;
  }
  public int getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return Integer.toString(myValue);
  }
  public static List<HierPriorityRegionEnum> getConstants() {
    List<HierPriorityRegionEnum> list = ListSequence.fromList(new LinkedList<HierPriorityRegionEnum>());
    ListSequence.fromList(list).addElement(HierPriorityRegionEnum._0);
    ListSequence.fromList(list).addElement(HierPriorityRegionEnum._1);
    ListSequence.fromList(list).addElement(HierPriorityRegionEnum._2);
    return list;
  }
  public static HierPriorityRegionEnum getDefault() {
    return HierPriorityRegionEnum._0;
  }
  public static HierPriorityRegionEnum parseValue(String value) {
    if (value == null) {
      return HierPriorityRegionEnum.getDefault();
    }
    if (value.equals(HierPriorityRegionEnum._0.getValueAsString())) {
      return HierPriorityRegionEnum._0;
    }
    if (value.equals(HierPriorityRegionEnum._1.getValueAsString())) {
      return HierPriorityRegionEnum._1;
    }
    if (value.equals(HierPriorityRegionEnum._2.getValueAsString())) {
      return HierPriorityRegionEnum._2;
    }
    return HierPriorityRegionEnum.getDefault();
  }
}
