package BSML.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum HierPrioritySchemeEnum {
  _0("PARENT", 0),
  _1("CHILD", 1);

  private final String myName;
  public String getName() {
    return myName;
  }
  private final int myValue;
  HierPrioritySchemeEnum(String name, int value) {
    myName = name;
    myValue = value;
  }
  public int getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return Integer.toString(myValue);
  }
  public static List<HierPrioritySchemeEnum> getConstants() {
    List<HierPrioritySchemeEnum> list = ListSequence.fromList(new LinkedList<HierPrioritySchemeEnum>());
    ListSequence.fromList(list).addElement(HierPrioritySchemeEnum._0);
    ListSequence.fromList(list).addElement(HierPrioritySchemeEnum._1);
    return list;
  }
  public static HierPrioritySchemeEnum getDefault() {
    return HierPrioritySchemeEnum._0;
  }
  public static HierPrioritySchemeEnum parseValue(String value) {
    if (value == null) {
      return HierPrioritySchemeEnum.getDefault();
    }
    if (value.equals(HierPrioritySchemeEnum._0.getValueAsString())) {
      return HierPrioritySchemeEnum._0;
    }
    if (value.equals(HierPrioritySchemeEnum._1.getValueAsString())) {
      return HierPrioritySchemeEnum._1;
    }
    return HierPrioritySchemeEnum.getDefault();
  }
}
