package BSML.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum InEventEnum {
  _0("RECEIVED IN FIRST SMALL", 0),
  _1("SYNTACTIC", 1),
  _2("HYBRID", 2);

  private final String myName;
  public String getName() {
    return myName;
  }
  private final int myValue;
  InEventEnum(String name, int value) {
    myName = name;
    myValue = value;
  }
  public int getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return Integer.toString(myValue);
  }
  public static List<InEventEnum> getConstants() {
    List<InEventEnum> list = ListSequence.fromList(new LinkedList<InEventEnum>());
    ListSequence.fromList(list).addElement(InEventEnum._0);
    ListSequence.fromList(list).addElement(InEventEnum._1);
    ListSequence.fromList(list).addElement(InEventEnum._2);
    return list;
  }
  public static InEventEnum getDefault() {
    return InEventEnum._0;
  }
  public static InEventEnum parseValue(String value) {
    if (value == null) {
      return InEventEnum.getDefault();
    }
    if (value.equals(InEventEnum._0.getValueAsString())) {
      return InEventEnum._0;
    }
    if (value.equals(InEventEnum._1.getValueAsString())) {
      return InEventEnum._1;
    }
    if (value.equals(InEventEnum._2.getValueAsString())) {
      return InEventEnum._2;
    }
    return InEventEnum.getDefault();
  }
}
