package BSML.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum MemoryProtocolEnum {
  _0("SMALL STEP", 0),
  _1("BIG STEP", 1);

  private final String myName;
  public String getName() {
    return myName;
  }
  private final int myValue;
  MemoryProtocolEnum(String name, int value) {
    myName = name;
    myValue = value;
  }
  public int getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return Integer.toString(myValue);
  }
  public static List<MemoryProtocolEnum> getConstants() {
    List<MemoryProtocolEnum> list = ListSequence.fromList(new LinkedList<MemoryProtocolEnum>());
    ListSequence.fromList(list).addElement(MemoryProtocolEnum._0);
    ListSequence.fromList(list).addElement(MemoryProtocolEnum._1);
    return list;
  }
  public static MemoryProtocolEnum getDefault() {
    return MemoryProtocolEnum._0;
  }
  public static MemoryProtocolEnum parseValue(String value) {
    if (value == null) {
      return MemoryProtocolEnum.getDefault();
    }
    if (value.equals(MemoryProtocolEnum._0.getValueAsString())) {
      return MemoryProtocolEnum._0;
    }
    if (value.equals(MemoryProtocolEnum._1.getValueAsString())) {
      return MemoryProtocolEnum._1;
    }
    return MemoryProtocolEnum.getDefault();
  }
}
