package BSML.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum OutEventEnum {
  _0("SYNTACTIC", 0),
  _1("GENERATED IN LAST SMALL", 1),
  _2("HYBRID", 2);

  private final String myName;
  public String getName() {
    return myName;
  }
  private final int myValue;
  OutEventEnum(String name, int value) {
    myName = name;
    myValue = value;
  }
  public int getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return Integer.toString(myValue);
  }
  public static List<OutEventEnum> getConstants() {
    List<OutEventEnum> list = ListSequence.fromList(new LinkedList<OutEventEnum>());
    ListSequence.fromList(list).addElement(OutEventEnum._0);
    ListSequence.fromList(list).addElement(OutEventEnum._1);
    ListSequence.fromList(list).addElement(OutEventEnum._2);
    return list;
  }
  public static OutEventEnum getDefault() {
    return OutEventEnum._0;
  }
  public static OutEventEnum parseValue(String value) {
    if (value == null) {
      return OutEventEnum.getDefault();
    }
    if (value.equals(OutEventEnum._0.getValueAsString())) {
      return OutEventEnum._0;
    }
    if (value.equals(OutEventEnum._1.getValueAsString())) {
      return OutEventEnum._1;
    }
    if (value.equals(OutEventEnum._2.getValueAsString())) {
      return OutEventEnum._2;
    }
    return OutEventEnum.getDefault();
  }
}
