package BSML.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum SmallStepConsistencyEnum {
  _0("SOURCE/TARGET ORTHOGONAL", 0),
  _1("ARENA ORTHOGONAL", 1);

  private final String myName;
  public String getName() {
    return myName;
  }
  private final int myValue;
  SmallStepConsistencyEnum(String name, int value) {
    myName = name;
    myValue = value;
  }
  public int getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return Integer.toString(myValue);
  }
  public static List<SmallStepConsistencyEnum> getConstants() {
    List<SmallStepConsistencyEnum> list = ListSequence.fromList(new LinkedList<SmallStepConsistencyEnum>());
    ListSequence.fromList(list).addElement(SmallStepConsistencyEnum._0);
    ListSequence.fromList(list).addElement(SmallStepConsistencyEnum._1);
    return list;
  }
  public static SmallStepConsistencyEnum getDefault() {
    return SmallStepConsistencyEnum._1;
  }
  public static SmallStepConsistencyEnum parseValue(String value) {
    if (value == null) {
      return SmallStepConsistencyEnum.getDefault();
    }
    if (value.equals(SmallStepConsistencyEnum._0.getValueAsString())) {
      return SmallStepConsistencyEnum._0;
    }
    if (value.equals(SmallStepConsistencyEnum._1.getValueAsString())) {
      return SmallStepConsistencyEnum._1;
    }
    return SmallStepConsistencyEnum.getDefault();
  }
}
